services:
  whisper_backend:
    container_name: whisper_backend2
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.cpu
    volumes:
      - ./setup_config/test_cpu_config.yaml:/usr/src/app/config.yaml
    ports:
      - 8000:8000
    command: [ "python", "client.py" ]
